Feature/channel 채널 소켓 살짝쿵 구현 해보았읍니다
42masterplan/ft_transcendence-back pull request #16
Opened 2023-11-18 08:53 UTC by saltwoodYJ

channel gateway 소켓 구현 하였구요
dto 랑 entity 대규모 변경이 있었습니다

2023-11-18 10:41 UTC, besyia0k0 requested changes

2023-11-18 10:41 UTC, besyia0k0 commented on src/feature/api/channel/infrastructure/channelMessage.entity.ts
create 함수는 다른 함수에 있어야 할 것 같아요!

2023-11-18 10:41 UTC, besyia0k0 commented on src/feature/api/users/application/use-case/users.use-case.ts
use-case의 리턴값으로는 User를 사용하는 것이 좋을 것 같습니당

2023-11-18 10:41 UTC, besyia0k0 commented on src/feature/api/users/infrastructure/user.repository.impl.ts
이 함수의 리턴값은 User가 맞는 것 같아요!

2023-11-18 10:41 UTC, besyia0k0 commented on src/feature/gateway/channel/channel.service.ts
service 파일에 repository에 있어야 할 로직이 분리되지 않은 것 같아요!
근데 이 부분은 확실하지 않고 잘 모르겠어서 같이 얘기해봐야할것같아요ㅠ

2023-11-22 11:55 UTC, jooocy commented
우선 Pr이너무 깁니다... 이러면 리뷰를 할수가 없어요

2023-11-22 11:57 UTC, jooocy commented on src/feature/gateway/channel/channel.service.ts
gateway는 컨트롤랑 같은 presentation layer에 있어야 합니다.

2023-11-22 12:00 UTC, jooocy commented
우선 머지하구 잘못된부분 다시 브랜치파서 작업해야할것같습니다. 이렇게 큰 pr있으면 다른사람들도 컨플릭때문에 작업할수가 없어요

2023-11-22 12:07 UTC, jooocy approved these changes
lgtm

2023-11-22 12:07 UTC, merged