feat(friend-request): implement accept reject friend reuqest
42masterplan/ft_transcendence-back pull request #38
Opened 2023-12-03 14:03 UTC by jooocy

## ✅ 풀\_리퀘스트 체크리스트

- [ ] PR 제목: [Feature/Fix/Refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [ ] commit message 가 적절한지 확인해주세요.
- [ ] 적절한 branch 로 요청했는지 확인해주세요.
- [ ] Assignees, Label 을 붙여주세요.
- [ ] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer 로 등록해주세요.
- [ ] PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

<br/>

## 🔄 변경 사항

친구 요청에대학 수락/거절 구현했습니다.
<br/>

## 📎 변경한 이유

- 이러한 이유 때문에 변경했습니다!

<br/>

closes: #Issue Number

## 👨🏻‍💻 테스트 체크리스트

- 이러한 테스트를 했어요!

<br/>

## 📌 변경 및 주의 사항

<br/>

2023-12-04 13:09 UTC, saltwoodYJ requested changes
그리고 npm run start:dev 했을때 빌드오류가 나요 userModule에서 의존성 오류나는것같아요

2023-12-04 13:49 UTC, jooocy commented on src/feature/api/users/infrastructure/repositories/friend-request.repository.ts
> +    friendRequest.id;
정신줄이 어디로 간거지

2023-12-04 14:46 UTC, besyia0k0 approved these changes
고생하셔씁니다 ~!! LGTM!

2023-12-05 12:28 UTC, saltwoodYJ approved these changes
lgtm

2023-12-09 06:36 UTC, merged